# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/File_Attention.ipynb (unless otherwise specified).

__all__ = []

import ast
import itertools
import json

# Cell
import os
from functools import partial
from operator import itemgetter

import attr
import gensim
import matplotlib.pyplot as plt
import mlutil
import numpy as np
import pandas as pd
import tqdm
from mlutil.feature_extraction import embeddings
from scarce_learn import zero_shot
from scarce_learn.zero_shot import devise_jax, devise_torch
from sklearn import feature_extraction, metrics, model_selection

from github_search import paperswithcode_tasks
