# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/Github_READMEs.ipynb (unless otherwise specified).

__all__ = ["get_readme", "try_decode", "get_readmes"]

# Cell

import requests

from tqdm.contrib import concurrent

# Cell


def get_readme(repo):
    url_pattern = "https://raw.githubusercontent.com/{}/master/README.md"
    result = requests.get(url_pattern.format(repo))
    if result.status_code == 200:
        return result.content
    else:
        return None


# Cell


def try_decode(s, codec="utf-8"):
    try:
        return s.decode(codec)
    except:
        return None


def get_readmes(df, max_workers):
    raw_readmes = concurrent.process_map(get_readme, df["repo"].to_list(), max_workers=max_workers)
    readmes = list(map(try_decode, raw_readmes))
    return readmes
