# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/Searching code with haystack.ipynb (unless otherwise specified).

__all__ = ['python_test_file_path', 'codesearch_df']

# Cell
import pprint
import numpy as np
import pandas as pd
import requests

from haystack import Finder
from haystack.database.elasticsearch import ElasticsearchDocumentStore
from haystack.database.elasticsearch import ElasticsearchDocumentStore

from haystack.retriever.dense import EmbeddingRetriever
from haystack.utils import print_answers


# Cell

python_test_file_path = '../data/CodeSearchNet/python/final/jsonl/test/python_test_0.jsonl.gz'
codesearch_df = pd.read_json(python_test_file_path, lines=True)