# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/Repo_Embedder.ipynb (unless otherwise specified).

__all__ = []

# Cell
import fasttext
import pandas as pd
import tokenize
import io
import keyword
import gensim


from github_search import python_tokens
from mlutil.feature_extraction import embeddings