# AUTOGENERATED! DO NOT EDIT! File to edit: notebooks/Query_Comment_Embeddings.ipynb (unless otherwise specified).

__all__ = []

# Cell

import os
import sys
import tqdm

from sklearn import feature_extraction, metrics
import numpy as np
import pandas as pd

import mlutil.parallel

import nltk
from gensim.models import doc2vec

import gensim
from github_search import repository_descriptions, neptune_util