[tool.poetry]
name = "github-search"
version = "0.1.0"
description = ""
authors = ["Jakub 'lambdaofgod' Bartczuk <bartczukkuba@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
scikit-learn = "^1.3.1"
nltk = "^3.8.1"
bs4 = "^0.0.1"
markdown = "^3.5"
attrs = "^23.1.0"
markdown2 = "^2.4.10"
#umap-learn = "^0.5.4"
stop-words = "^2018.7.23"
docstring-parser = "^0.15"
rank-bm25 = "^0.2.1"
poethepoet = "^0.24.4"
six = "^1.16.0"
zenml = "^0.47.0"
returns = "^0.22.0"
pydantic-core = "^2.14.4"
pandera = "^0.17.2"
ploomber = "^0.23.0"
farm-haystack = "^1.22.1"
astunparse = "^1.6.3"
csrgraph = "^0.1.28"
igraph = "^0.11.3"
nodevectors = "^0.1.23"
polars = "^0.19.15"
pandas-parallel-apply = "^2.2"
h5py = "^3.10.0"
livelossplot = "^0.5.5"
torch = "^2.1.1"
bounter = "^1.2.0"
bleurt = {git = "https://github.com/google-research/bleurt.git"}
mlutil = {git = "https://github.com/lambdaofgod/mlutil.git"}
mlutil-rust = {git = "https://github.com/lambdaofgod/mlutil_rust.git"}
findkit = {git= "https://github.com/lambdaofgod/findkit.git"}
tgutil = {git = "https://github.com/lambdaofgod/tgutil.git"}
paperswithcode = {git = "https://github.com/lambdaofgod/paperswithcode-client.git"}

[tool.poetry.group.dev.dependencies]
torch-geometric = "^2.4.0"
fastai = "^2.7.13"
neptune = "^1.8.5"
black = "^23.11.0"
ipdb = "^0.13.13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poe.tasks.generation_pipeline]
script = "github_search.pipelines.pipeline:run_generation(sampling, generation_method, prompting_method)"
args = ["sampling", "generation_method", "prompting_method"]


[tool.poe.tasks.metrics_pipeline]
script = "github_search.pipelines.pipeline:metrics_pipeline(ir_config_path='conf/pipeline/ir_config.yaml',embedder_config_path='conf/pipeline/retrieval.yaml',column_config_path='conf/pipeline/column_configs.yaml',search_df_path='output/nbow_data_test.parquet',paperswithcode_path='data/paperswithcode_with_tasks.csv')"
