[project]
name = "github-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aider>=0.2.6",
    "apache-airflow==2.8.4",
    "beir>=2.0.0",
    "comment-parser>=1.2.4",
    "dagster>=1.6.5",
    "dspy-ai==2.4.5",
    "fire>=0.7.0",
    "ipykernel>=6.29.5",
    "metaflow>=2.12.25",
    "mlflow==2.16.2",
    "mlutil",
    "numba>=0.60.0",
    "openinference-instrumentation-dspy==0.1.6",
    "pandera>=0.20.4",
    "pendulum==2.1.2",
    "pytrec-eval>=0.5",
    "toolz>=1.0.0",
    "typing-extensions>=4.12.2",
    "visutils",
]

[tool.uv]
prerelease = "allow"
dev-dependencies = [
    "dagster-webserver>=1.6.5",
]

[tool.uv.sources]
mlutil = { git = "https://github.com/lambdaofgod/mlutil" }
visutils = { path = "../visualization" }

[tool.dagster]
module_name = "github_search.pipelines.dagster.definitions"
code_location_name = "github_search"
