dependencies_with_generated_tasks:
  document_cols:
  - dependencies
  - tasks
  list_cols: []
  query_col: true_tasks
dependencies:
  document_cols:
  - dependencies
  list_cols: []
  query_col: true_tasks
generated_tasks:
  document_cols:
  - tasks
  list_cols: []
  query_col: true_tasks
