column_config:
  document_cols:
  - generated_tasks
  - truncated_dependencies
  list_cols: []
  query_col: tasks
embedder_config:
  doc_max_length: 100
  document_embedder_path: ../../output/models/best_model/dependencies/nbow_document_1
  query_embedder_path: ../../output/models/best_model/dependencies/nbow_query_1
  query_max_length: null
search_df_path: ../output/nbow_data_test.parquet
