mlflow:
  tracking_uri: "http://localhost:5000"
  experiment_name: "Code2Doc Pipeline"

pipeline:
  repos_df_path: "path/to/repos_df.json"
  python_code_path: "path/to/python_code.parquet"
  n_repos_per_task: 10
  min_task_size: 5
  max_task_size: 500
  max_random_baseline_score: 0.5
  lm_model_name: "codellama"
  lm_base_url: "http://localhost:11434"
  files_per_repo: 10
