source "https://rubygems.org"

gem 'github-pages', group: :jekyll_plugins

# Added at 2019-11-25 10:11:40 -0800 by jhoward:
gem "addressable", ">= 2.8.0"
gem "nokogiri", ">= 1.13.2"
gem "jekyll", ">= 3.7"
gem "jekyll-remote-theme"
