dependencies_with_generated_tasks:
  document_cols:
  - generated_tasks
  - dependencies
  list_cols: []
  query_col: tasks
dependencies:
  document_cols:
  - generated_tasks
  - dependencies
  list_cols: []
  query_col: tasks
generated_tasks:
  document_cols:
  - generated_tasks
  - dependencies
  list_cols: []
  query_col: tasks
